name: make model
on:
  push:
    paths:
      - 'model/'
  workflow_dispatch:
      
jobs:
  create_model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Python Install
        run: |
          python -m pip install --upgrade pip
          pip install mecab-python3
          pip install unidic-lite
          pip install feedparser

      - name: make
        run: |
          python model/model-make.py
          cat model/
          cat ./

      - name: Update File
        run: |
          if ! git diff --exit-code --quiet
          then
           git add --update
            git config --global user.name ${{ secrets.USER_NAME }}
            git config --global user.email ${{ secrets.MAIL_ADDRESS }}
            git commit -m "Update Content"
            git push
          fi
